const logoInput=document.getElementById('logoInput');
const uploadEmpty=document.getElementById('uploadEmpty');
const uploadFilled=document.getElementById('uploadFilled');
const uploadThumb=document.getElementById('uploadThumb');
const fileName=document.getElementById('fileName');
const keychainEmpty=document.getElementById('keychainEmpty');
const keychainWrap=document.getElementById('keychainWrap');
const canvas=document.getElementById('keychainCanvas');
const ctx=canvas.getContext('2d');
const profileLogo=document.getElementById('profileLogo');
const profilePlaceholder=document.getElementById('profilePlaceholder');
let originalData='';

function readFile(file){if(!file||!file.type.startsWith('image/'))return;fileName.textContent=file.name;const r=new FileReader();r.onload=()=>{originalData=r.result;processLogo()};r.readAsDataURL(file)}

function hasRealTransparency(c,x){const d=x.getImageData(0,0,c.width,c.height).data;let t=0,n=0,step=Math.max(1,Math.floor(Math.sqrt((c.width*c.height)/50000)));for(let y=0;y<c.height;y+=step)for(let xx=0;xx<c.width;xx+=step){const a=d[(y*c.width+xx)*4+3];n++;if(a<220)t++}return n&&t/n>.015}

function borderStats(c,x){const d=x.getImageData(0,0,c.width,c.height).data;const band=Math.max(2,Math.round(Math.min(c.width,c.height)*.05));const samples=[];const step=Math.max(1,Math.round(Math.min(c.width,c.height)/160));const add=(xx,y)=>{const i=(y*c.width+xx)*4;if(d[i+3]>30)samples.push([d[i],d[i+1],d[i+2]])};for(let y=0;y<c.height;y+=step)for(let xx=0;xx<band;xx+=step){add(xx,y);add(c.width-1-xx,y)}for(let xx=0;xx<c.width;xx+=step)for(let y=0;y<band;y+=step){add(xx,y);add(xx,c.height-1-y)}if(!samples.length)return null;const avg=[0,0,0];for(const s of samples){avg[0]+=s[0];avg[1]+=s[1];avg[2]+=s[2]}avg[0]/=samples.length;avg[1]/=samples.length;avg[2]/=samples.length;let variance=0;for(const s of samples){const dr=s[0]-avg[0],dg=s[1]-avg[1],db=s[2]-avg[2];variance+=Math.sqrt(dr*dr+dg*dg+db*db)}return{avg,variance:variance/samples.length}}

function removeEdgeBackground(c,x){if(hasRealTransparency(c,x))return;const s=borderStats(c,x);if(!s)return;const {avg,variance}=s;if(variance>95)return;const p=x.getImageData(0,0,c.width,c.height),d=p.data,w=c.width,h=c.height;const seen=new Uint8Array(w*h),qx=new Int32Array(w*h),qy=new Int32Array(w*h);let head=0,tail=0;const hard=Math.max(42,Math.min(85,45+variance*.45)),soft=hard+38;const distAt=(xx,y)=>{const i=(y*w+xx)*4,dr=d[i]-avg[0],dg=d[i+1]-avg[1],db=d[i+2]-avg[2];return Math.sqrt(dr*dr+dg*dg+db*db)};const add=(xx,y)=>{const pos=y*w+xx;if(seen[pos])return;const i=pos*4;if(d[i+3]<20||distAt(xx,y)<=soft){seen[pos]=1;qx[tail]=xx;qy[tail]=y;tail++}};for(let xx=0;xx<w;xx++){add(xx,0);add(xx,h-1)}for(let y=0;y<h;y++){add(0,y);add(w-1,y)}while(head<tail){const xx=qx[head],y=qy[head];head++;const i=(y*w+xx)*4,dist=distAt(xx,y);if(dist<=hard)d[i+3]=0;else if(dist<soft)d[i+3]=Math.min(d[i+3],Math.round(255*(dist-hard)/(soft-hard)));if(xx>0)add(xx-1,y);if(xx<w-1)add(xx+1,y);if(y>0)add(xx,y-1);if(y<h-1)add(xx,y+1)}x.putImageData(p,0,0)}

function cropToContent(source){const sx=source.getContext('2d',{willReadFrequently:true}),p=sx.getImageData(0,0,source.width,source.height),d=p.data;let minX=source.width,minY=source.height,maxX=-1,maxY=-1;for(let y=0;y<source.height;y++)for(let x=0;x<source.width;x++){const a=d[(y*source.width+x)*4+3];if(a>35){if(x<minX)minX=x;if(x>maxX)maxX=x;if(y<minY)minY=y;if(y>maxY)maxY=y}}if(maxX<0)return source;const rawW=maxX-minX+1,rawH=maxY-minY+1,margin=Math.max(6,Math.round(Math.max(rawW,rawH)*.05));minX=Math.max(0,minX-margin);minY=Math.max(0,minY-margin);maxX=Math.min(source.width-1,maxX+margin);maxY=Math.min(source.height-1,maxY+margin);const out=document.createElement('canvas');out.width=maxX-minX+1;out.height=maxY-minY+1;out.getContext('2d').drawImage(source,minX,minY,out.width,out.height,0,0,out.width,out.height);return out}

function processLogo(){if(!originalData)return;const img=new Image();img.onload=()=>{const max=1400,scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(img,0,0,c.width,c.height);removeEdgeBackground(c,x);renderAll(cropToContent(c).toDataURL('image/png'))};img.src=originalData}

function renderAll(data){uploadThumb.src=data;uploadEmpty.classList.add('hidden');uploadFilled.classList.remove('hidden');keychainEmpty.classList.add('hidden');keychainWrap.classList.remove('hidden');profileLogo.src=data;profileLogo.style.display='block';profilePlaceholder.style.display='none';drawKeychain(data)}

function alphaMaskFromImage(img,w,h,x,y){const m=document.createElement('canvas');m.width=canvas.width;m.height=canvas.height;const mx=m.getContext('2d',{willReadFrequently:true});mx.drawImage(img,x,y,w,h);const p=mx.getImageData(0,0,m.width,m.height),d=p.data;for(let i=0;i<d.length;i+=4){const a=d[i+3];d[i]=255;d[i+1]=255;d[i+2]=255;d[i+3]=a>18?a:0}mx.putImageData(p,0,0);return m}
function coloredLayer(mask,fillStyle){const layer=document.createElement('canvas');layer.width=canvas.width;layer.height=canvas.height;const lx=layer.getContext('2d');lx.drawImage(mask,0,0);lx.globalCompositeOperation='source-in';lx.fillStyle=fillStyle;lx.fillRect(0,0,layer.width,layer.height);return layer}
function drawKeychain(data){const img=new Image();img.onload=()=>{ctx.clearRect(0,0,canvas.width,canvas.height);const pad=18,s=Math.min((canvas.width-pad*2)/img.width,(canvas.height-pad*2)/img.height),w=img.width*s,h=img.height*s,x=(canvas.width-w)/2,y=(canvas.height-h)/2,mask=alphaMaskFromImage(img,w,h,x,y),radius=Math.max(9,Math.round(Math.min(w,h)*.045));const bodyMask=document.createElement('canvas');bodyMask.width=canvas.width;bodyMask.height=canvas.height;const bx=bodyMask.getContext('2d');for(let dy=-radius;dy<=radius;dy+=2)for(let dx=-radius;dx<=radius;dx+=2)if(dx*dx+dy*dy<=radius*radius)bx.drawImage(mask,dx,dy);const body=coloredLayer(bodyMask,'#22242d');ctx.save();ctx.shadowColor='rgba(0,0,0,.62)';ctx.shadowBlur=24;ctx.shadowOffsetY=18;ctx.drawImage(body,0,0);ctx.restore();const goldLayer=document.createElement('canvas');goldLayer.width=canvas.width;goldLayer.height=canvas.height;const gx=goldLayer.getContext('2d'),gold=gx.createLinearGradient(0,y,0,y+h);gold.addColorStop(0,'#f0d990');gold.addColorStop(.45,'#d4ad57');gold.addColorStop(1,'#a77b2f');gx.fillStyle=gold;gx.fillRect(0,0,goldLayer.width,goldLayer.height);gx.globalCompositeOperation='destination-in';gx.drawImage(mask,0,0);ctx.drawImage(goldLayer,0,0)};img.src=data}

logoInput.addEventListener('change',e=>readFile(e.target.files[0]));const dz=document.getElementById('dropZone');['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.style.borderColor='#7159df'}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.style.borderColor=''}));dz.addEventListener('drop',e=>{const f=e.dataTransfer.files[0];if(f)readFile(f)});const bindings=[['company','companyPreview'],['whatsapp','waPreview'],['instagram','igPreview'],['website','webPreview']];bindings.forEach(([a,b])=>{const el=document.getElementById(a),out=document.getElementById(b);el.addEventListener('input',()=>out.textContent=el.value.trim()||el.placeholder)});document.getElementById('orderBtn').addEventListener('click',e=>{e.preventDefault();const company=document.getElementById('company').value.trim()||'بدون اسم';window.open(`https://wa.me/?text=${encodeURIComponent(`مرحبا، جربت معاينة الميدالية والموقع لشركة ${company} وأريد الاستفسار عن الطلب.`)}`,'_blank')});